// Generated by O/R mapper generator ver 0.1

#import <UIKit/UIKit.h>
#import "ORRecord.h"

@interface Person : ORRecord {
    NSString* name;
    NSDate* register_date;
    NSDate* birth_date;
    NSDate* marriage_date;
    NSDate* death_date;
}

@property(nonatomic,retain) NSString* name;
@property(nonatomic,retain) NSDate* register_date;
@property(nonatomic,retain) NSDate* birth_date;
@property(nonatomic,retain) NSDate* marriage_date;
@property(nonatomic,retain) NSDate* death_date;

+ (BOOL)migrate;

+ (NSMutableArray *)find_cond:(NSString *)cond;
+ (Person *)find:(int)pid;
- (void)delete;
+ (void)delete_cond:(NSString *)cond;
+ (void)delete_all;

// internal functions
+ (NSString *)tableName;
- (void)insert;
- (void)update;
- (void)_loadRow:(dbstmt *)stmt;

@end
