// Generated by O/R mapper generator ver 0.1

#import "Database.h"
#import "Person.h"

@implementation Person

@synthesize name;
@synthesize register_date;
@synthesize birth_date;
@synthesize marriage_date;
@synthesize death_date;

- (id)init
{
    self = [super init];
    return self;
}

- (void)dealloc
{
    [name release];
    [register_date release];
    [birth_date release];
    [marriage_date release];
    [death_date release];
    [super dealloc];
}

/**
  @brief Migrate database table

  @return YES - table was newly created, NO - table already exists
*/

+ (BOOL)migrate
{
    NSArray *columnTypes = [NSArray arrayWithObjects:
        @"name", @"TEXT",
        @"register_date", @"DATE",
        @"birth_date", @"DATE",
        @"marriage_date", @"DATE",
        @"death_date", @"DATE",
        nil];

    return [super migrate:columnTypes];
}

/**
  @brief get all records matche the conditions

  @param cond Conditions (WHERE phrase and so on)
  @return array of records
*/
+ (NSMutableArray *)find_cond:(NSString *)cond
{
    NSMutableArray *array = [[[NSMutableArray alloc] init] autorelease];
    Database *db = [Database instance];
    dbstmt *stmt;

    NSString *sql;
    if (cond == nil) {
        sql = @"SELECT * FROM Person;";
    } else {
        sql = [NSString stringWithFormat:@"SELECT * FROM Person %@;", cond];
    }  

    stmt = [db prepare:sql];
    while ([stmt step] == SQLITE_ROW) {
        Person *e = [[[Person alloc] init] autorelease];
        [e _loadRow:stmt];
        [array addObject:e];
    }
    return array;
}

/**
  @brief get the record matchs the id

  @param pid Primary key of the record
  @return record
*/
+ (Person *)find:(int)pid
{
    Database *db = [Database instance];

    dbstmt *stmt = [db prepare:@"SELECT * FROM Person WHERE id = ?;"];
    [stmt bindInt:0 val:pid];
    if ([stmt step] != SQLITE_ROW) {
        return nil;
    }

    Person *e = [[[Person alloc] init] autorelease];
    [e _loadRow:stmt];
 
    return e;
}

- (void)_loadRow:(dbstmt *)stmt
{
    self.pid = [stmt colInt:0];
    self.name = [stmt colString:1];
    self.register_date = [stmt colDate:2];
    self.birth_date = [stmt colDate:3];
    self.marriage_date = [stmt colDate:4];
    self.death_date = [stmt colDate:5];

    isInserted = YES;
}

+ (NSString *)tableName
{
    return @"Person";
}

- (void)insert
{
    [super insert];

    Database *db = [Database instance];
    dbstmt *stmt;
    
    [db beginTransaction];
    stmt = [db prepare:@"INSERT INTO Person VALUES(NULL,?,?,?,?,?);"];

    [stmt bindString:0 val:name];
    [stmt bindDate:1 val:register_date];
    [stmt bindDate:2 val:birth_date];
    [stmt bindDate:3 val:marriage_date];
    [stmt bindDate:4 val:death_date];
    [stmt step];

    self.pid = [db lastInsertRowId];

    [db commitTransaction];
    isInserted = YES;
}

- (void)update
{
    [super update];

    Database *db = [Database instance];
    [db beginTransaction];

    dbstmt *stmt = [db prepare:@"UPDATE Person SET "
        "name = ?"
        ",register_date = ?"
        ",birth_date = ?"
        ",marriage_date = ?"
        ",death_date = ?"
        " WHERE id = ?;"];
    [stmt bindString:0 val:name];
    [stmt bindDate:1 val:register_date];
    [stmt bindDate:2 val:birth_date];
    [stmt bindDate:3 val:marriage_date];
    [stmt bindDate:4 val:death_date];
    [stmt bindInt:5 val:pid];

    [stmt step];
    [db commitTransaction];
}

/**
  @brief Delete record
*/
- (void)delete
{
    Database *db = [Database instance];

    dbstmt *stmt = [db prepare:@"DELETE FROM Person WHERE id = ?;"];
    [stmt bindInt:0 val:pid];
    [stmt step];
}

/**
  @brief Delete all records
*/
+ (void)delete_cond:(NSString *)cond
{
    Database *db = [Database instance];

    if (cond == nil) {
        cond = @"";
    }
    NSString *sql = [NSString stringWithFormat:@"DELETE FROM Person %@;", cond];
    [db exec:sql];
}

+ (void)delete_all
{
    [Person delete_cond:nil];
}

@end
